import { tagHighlighter, tags } from "@lezer/highlight";

export const classHighlighter = tagHighlighter([
  { tag: tags.link, class: "cm-link" },
  { tag: tags.heading, class: "cm-heading" },
  { tag: tags.emphasis, class: "cm-emphasis" },
  { tag: tags.strong, class: "cm-strong" },
  { tag: tags.keyword, class: "cm-keyword" },
  { tag: tags.atom, class: "cm-meta" },
  { tag: tags.bool, class: "cm-bool" },
  { tag: tags.url, class: "cm-url" },
  { tag: tags.labelName, class: "cm-label" },
  { tag: tags.inserted, class: "cm-inserted" },
  { tag: tags.deleted, class: "cm-deleted" },
  { tag: tags.literal, class: "cm-literal" },
  { tag: tags.string, class: "cm-string" },
  { tag: tags.attributeValue, class: "cm-string" },
  { tag: tags.number, class: "cm-number" },
  {
    tag: [tags.regexp, tags.escape, tags.special(tags.string)],
    class: "cm-string-2",
  },
  { tag: tags.variableName, class: "cm-variable" },
  { tag: tags.local(tags.variableName), class: "cm-local" },
  {
    tag: tags.definition(tags.variableName),
    class: "cm-definition",
  },
  { tag: tags.special(tags.variableName), class: "cm-variable-2" },
  {
    tag: tags.definition(tags.propertyName),
    class: "cm-definition",
  },
  { tag: tags.typeName, class: "cm-type" },
  { tag: tags.namespace, class: "cm-namespace" },
  { tag: tags.className, class: "cm-class" },
  { tag: tags.macroName, class: "cm-macro" },
  { tag: tags.propertyName, class: "cm-property" },
  { tag: tags.attributeName, class: "cm-attribute" },
  { tag: tags.operator, class: "cm-operator" },
  { tag: [tags.comment, tags.contentSeparator], class: "cm-comment" },
  { tag: tags.meta, class: "cm-meta" },
  { tag: tags.processingInstruction, class: "cm-meta" },
  { tag: tags.invalid, class: "cm-invalid" },
  { tag: tags.punctuation, class: "cm-punctuation" },
  { tag: tags.bracket, class: "cm-bracket" },
  { tag: tags.strikethrough, class: "cm-line-through" },
]);
