import { md5, parseLinktext, stripHeadingForLink } from "./utils";
import type { App } from "./context.svelte";
import { EventDispatcher } from "./events";
import { logging } from "./logging";
import {
  defaultLinkSettings,
  getLinkPath,
  normalizeVaultPath,
  type VaultIndex,
} from "./links";
import {
  basename,
  TFile,
  type TAbstractFile,
  APP_DATABASE_SCHEMA_VERSION,
  type AppDatabaseIndexedFile,
  type AppDatabaseLinkRecord,
  type AppDatabasePropertyRecord,
  type AppDatabaseTagRecord,
  type MetadataCacheSnapshot,
  getAdapterVaultId,
  ScopedVaultStore,
  structuralLinkKind,
} from "$lib/storage";
import { debounce } from "lodash-es";
import { dirname, resolvePath } from "./storage/path";
import type { NotificationProgressHandle } from "./notifications";

export const METADATA_CACHE_BACKUP_PATH = ".lapis/cache/metadata-cache.json";

const METADATA_CACHE_BACKUP_KIND = "lapis.metadata-cache.snapshot";
const METADATA_CACHE_BACKUP_SCHEMA_VERSION = 1;
const METADATA_CACHE_BACKUP_THROTTLE_MS = 30_000;

function yieldToUi(): Promise<void> {
  return new Promise((resolve) => {
    setTimeout(resolve, 0);
  });
}

type MetadataCacheBackupV1 = {
  kind: typeof METADATA_CACHE_BACKUP_KIND;
  schemaVersion: typeof METADATA_CACHE_BACKUP_SCHEMA_VERSION;
  appDatabaseSchemaVersion: number;
  createdAt: number;
  updatedAt: number;
  sourceVaultId?: string;
  snapshot: MetadataCacheSnapshot;
};

function notify(message: string): void {
  const Notice = (globalThis as any).Notice;
  if (typeof Notice === "function") {
    new Notice(message);
  } else {
    console.warn(message);
  }
}

function isMetadataCacheSnapshot(
  value: unknown,
): value is MetadataCacheSnapshot {
  if (!value || typeof value !== "object") {
    return false;
  }
  const candidate = value as Partial<MetadataCacheSnapshot>;
  return (
    isRecord(candidate.fileCache) &&
    isRecord(candidate.metadataCache) &&
    isRecord(candidate.resolvedLinks) &&
    isRecord(candidate.unresolvedLinks)
  );
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return Boolean(value && typeof value === "object" && !Array.isArray(value));
}

function parseMetadataCacheBackup(raw: string): MetadataCacheBackupV1 | null {
  let parsed: unknown;
  try {
    parsed = JSON.parse(raw);
  } catch {
    return null;
  }
  if (!isRecord(parsed)) {
    return null;
  }
  if (
    parsed.kind !== METADATA_CACHE_BACKUP_KIND ||
    parsed.schemaVersion !== METADATA_CACHE_BACKUP_SCHEMA_VERSION ||
    typeof parsed.appDatabaseSchemaVersion !== "number" ||
    typeof parsed.createdAt !== "number" ||
    typeof parsed.updatedAt !== "number" ||
    !isMetadataCacheSnapshot(parsed.snapshot)
  ) {
    return null;
  }
  if (
    "sourceVaultId" in parsed &&
    parsed.sourceVaultId !== undefined &&
    typeof parsed.sourceVaultId !== "string"
  ) {
    return null;
  }
  return parsed as MetadataCacheBackupV1;
}

/**
 * Location within a Markdown document
 *
 * @public
 */
export interface Loc {
  /**
   * Line number. 0-based.
   *
   * @public
   */
  line: number;
  /**
   * Column number.
   *
   * @public
   */
  col: number;
  /**
   * Number of characters from the beginning of the file.
   *
   * @public
   */
  offset: number;
}

/**
 * Describes a text range in a Markdown document.
 *
 * @public
 */
export interface Pos {
  /**
   * Starting location.
   *
   * @public
   */
  start: Loc;
  /**
   * End location.
   *
   * @public
   */
  end: Loc;
}

export interface CacheItem {
  /**
   * Position of this item in the note.
   *
   * @public
   */
  position: Pos;
}

export interface HeadingCache extends CacheItem {
  /** @public */
  heading: string;
  /**
   * Number between 1 and 6.
   *
   * @public
   */
  level: number;
}

export interface TagCache extends CacheItem {
  /** @public */
  tag: string;
}

export interface FootnoteCache extends CacheItem {
  /** @public */
  id: string;
}

export interface BlockCache extends CacheItem {
  /** @public */
  id: string;
}

/**
 * Base interface for items that point to a different location.
 *
 * @public
 */
export interface Reference {
  /**
   * Link destination.
   *
   * @public
   */
  link: string;
  /**
   * Contains the text as it's written in the document. Not available on
   * Publish.
   *
   * @public
   */
  original: string;
  /**
   * Available if title is different from link text, in the case of `[[page
   * name|display name]]` this will return `display name`
   *
   * @public
   */
  displayText?: string;
}

export interface ReferenceCache extends Reference, CacheItem {}

export interface LinkCache extends ReferenceCache {
  heading?: string;
}

export interface EmbedCache extends ReferenceCache {}

export interface SectionCache extends CacheItem {
  /**
   * The block ID of this section, if defined.
   *
   * @public
   */
  id?: string | undefined;
  /**
   * The type string generated by the parser. Typing is non-exhaustive, more
   * types can be available than are documented here.
   *
   * @public
   */
  type:
    | "blockquote"
    | "callout"
    | "code"
    | "element"
    | "footnoteDefinition"
    | "heading"
    | "html"
    | "list"
    | "paragraph"
    | "table"
    | "text"
    | "thematicBreak"
    | "yaml"
    | string;
}

export interface ListItemCache extends CacheItem {
  /**
   * The block ID of this list item, if defined.
   *
   * @public
   */
  id?: string | undefined;
  /**
   * A single character indicating the checked status of a task. The space
   * character `' '` is interpreted as an incomplete task. An other character is
   * interpreted as completed task. `undefined` if this item isn't a task.
   *
   * @public
   */
  task?: string | undefined;
  /**
   * Line number of the parent list item (position.start.line). If this item has
   * no parent (e.g. it's a root level list), then this value is the negative of
   * the line number of the first list item (start of the list).
   *
   * Can be used to deduce which list items belongs to the same group
   * (item1.parent === item2.parent). Can be used to reconstruct hierarchy
   * information (parentItem.position.start.line === childItem.parent).
   *
   * @public
   */
  parent: number;
}

export interface FootnoteRefCache extends CacheItem {
  /** @public */
  id: string;
}

export interface ReferenceLinkCache extends CacheItem {
  /** @public */
  id: string;
  /** @public */
  link: string;
}
export interface FrontMatterCache {
  /** @public */
  [key: string]: any;
}

export interface FrontMatterInfo {
  /** @public Whether this file has a frontmatter block */
  exists: boolean;
  /** @public String representation of the frontmatter */
  frontmatter: string;
  /** @public Start of the frontmatter contents (excluding the ---) */
  from: number;
  /** @public End of the frontmatter contents (excluding the ---) */
  to: number;
  /** @public Offset where the frontmatter block ends (including the ---) */
  contentStart: number;
}

export function getFrontMatterInfo(content: string): FrontMatterInfo {
  const regexp = /^-{3}\s*[\n\r](.*?)[\n\r]-{3}\s*[\n\r]+/s;
  let match: RegExpExecArray | null;
  if ((match = regexp.exec(content))) {
    return {
      exists: true,
      frontmatter: match[1],
      from: match.index,
      to: regexp.lastIndex,
      contentStart: match[0].length,
    };
  }
  return { exists: false, frontmatter: "", from: 0, to: 0, contentStart: 0 };
}

export function parseFrontMatterTags(frontmatter: any | null): string[] | null {
  if (!frontmatter) return null;
  const tags: string[] = [];
  const pushTag = (value: unknown) => {
    const tag = value?.toString().trim();
    if (!tag) {
      return;
    }
    const normalized = tag.startsWith("#") ? tag : `#${tag}`;
    if (/^#[/a-zA-Z0-9_-]+$/.test(normalized)) {
      tags.push(normalized);
    }
  };
  if (typeof frontmatter === "object") {
    for (const [key, value] of Object.entries(frontmatter)) {
      const id = key.toLowerCase().trim();
      if (id === "tags" || id === "tag") {
        if (Array.isArray(value)) {
          value.forEach(pushTag);
        } else if (typeof value === "string") {
          value.split(/[,;\s]+/).forEach(pushTag);
        }
      }
    }
  }
  return tags;
}

export function parseFrontMatterStringArray(
  frontmatter: any | null,
  key: string,
): string[] | null {
  if (!frontmatter || !(key in frontmatter)) return null;
  const value = frontmatter[key];
  if (Array.isArray(value)) {
    return value.map((item) => item.toString());
  }
  if (typeof value === "string") {
    return value
      .split(",")
      .map((item) => item.trim())
      .filter(Boolean);
  }
  return null;
}

export function parseFrontMatterAliases(
  frontmatter: any | null,
): string[] | null {
  return (
    parseFrontMatterStringArray(frontmatter, "aliases") ??
    parseFrontMatterStringArray(frontmatter, "alias")
  );
}

export function parseFrontMatterEntry(
  frontmatter: any | null,
  key: string,
): any | null {
  return frontmatter?.[key] ?? null;
}

export interface FrontmatterLinkCache extends Reference {
  /** @public */
  key: string;
}

export interface CachedMetadata {
  /**
   * Position of the frontmatter in the file.
   *
   * @public
   */
  frontmatterPosition?: Pos;
  links?: LinkCache[];
  embeds?: EmbedCache[];
  tags?: TagCache[];
  /**
   * Sections are root level markdown blocks, which can be used to divide the
   * document up.
   *
   * @public
   */
  sections?: SectionCache[];
  listItems?: ListItemCache[];
  frontmatter?: FrontMatterCache;
  headings?: HeadingCache[];
  footnotes?: FootnoteCache[];
  footnoteRefs?: FootnoteRefCache[];
  referenceLinks?: ReferenceLinkCache[];
  blocks?: Record<string, BlockCache>;
}

export interface SubpathResult {
  start: Loc;
  end: Loc | null;
}

export interface HeadingSubpathResult extends SubpathResult {
  type: "heading";
  current: HeadingCache;
  next: HeadingCache | null;
}

export interface BlockSubpathResult extends SubpathResult {
  type: "block";
  block: BlockCache;
  list?: ListItemCache;
}

export interface FootnoteSubpathResult extends SubpathResult {
  type: "footnote";
  footnote: FootnoteCache;
}

export function iterateRefs(
  refs: Reference[],
  cb: (ref: Reference) => boolean | void,
): boolean {
  for (const ref of refs) {
    if (cb(ref)) return true;
  }
  return false;
}

function uniquePaths(paths: Iterable<string>): string[] {
  return [...new Set([...paths].filter(Boolean))];
}

export function iterateCacheRefs(
  cache: CachedMetadata,
  cb: (ref: ReferenceCache) => boolean | void,
): boolean {
  return iterateRefs(
    [...(cache.links ?? []), ...(cache.embeds ?? [])],
    cb as (ref: Reference) => boolean | void,
  );
}

export function resolveSubpath(
  cache: CachedMetadata,
  subpath: string,
): HeadingSubpathResult | BlockSubpathResult | FootnoteSubpathResult | null {
  const target = subpath.replace(/^#/, "").trim();
  if (!target) return null;

  if (target.startsWith("^")) {
    const id = target.slice(1);
    const block = cache.blocks?.[id];
    if (!block) return null;
    return {
      type: "block",
      block,
      list: cache.listItems?.find((item) => item.id === id),
      start: block.position.start,
      end: block.position.end,
    };
  }

  const footnoteId = /^\[(.+)]$/.exec(target)?.[1];
  if (footnoteId) {
    const footnote = cache.footnotes?.find((item) => item.id === footnoteId);
    if (!footnote) return null;
    return {
      type: "footnote",
      footnote,
      start: footnote.position.start,
      end: footnote.position.end,
    };
  }

  const normalized = stripHeadingForLink(target).toLowerCase();
  const headings = cache.headings ?? [];
  const index = headings.findIndex((heading) => {
    return stripHeadingForLink(heading.heading).toLowerCase() === normalized;
  });
  if (index === -1) return null;

  const current = headings[index];
  const next = headings[index + 1] ?? null;
  return {
    type: "heading",
    current,
    next,
    start: current.position.start,
    end: next?.position.start ?? null,
  };
}

export type MetadataProcessor = {
  read: (
    data: string,
    context: { cache: CachedMetadata; file: TFile },
  ) => Promise<CachedMetadata>;
  write: (cache: CachedMetadata) => string;
};

export type IndexedProjectionContribution = {
  task?: import("./storage/task-projection").AppDatabaseTaskRecord | null;
};

export type IndexedProjectionContributor = {
  project(input: {
    file: TFile;
    content: string;
    cache: CachedMetadata;
  }):
    | IndexedProjectionContribution
    | null
    | Promise<IndexedProjectionContribution | null>;
};

function clearObject(data: Record<string, unknown>) {
  for (const key of Object.keys(data)) {
    delete data[key];
  }
}

function parseValue<T>(key: string, value: string, defaultValue: T): T {
  if (value) {
    try {
      const data = JSON.parse(value);
      if (data) {
        return data as T;
      }
      return defaultValue;
    } catch (e) {
      console.error(`Unable to read ${key}:`, e);
      notify(`Error reading ${key}: ${e}`);
      return defaultValue;
    }
  }
  return defaultValue;
}

function frontmatterValueType(value: unknown): string {
  if (Array.isArray(value)) return "array";
  if (value === null) return "null";
  return typeof value;
}

function tagParts(tag: string): { parts: string[]; hierarchy: string[] } {
  const parts = tag
    .replace(/^#/, "")
    .split("/")
    .map((part) => part.trim())
    .filter(Boolean);
  const hierarchy: string[] = [];
  for (let index = 1; index <= parts.length; index++) {
    hierarchy.push(parts.slice(0, index).join("/"));
  }
  return { parts, hierarchy };
}

/**
 * Indexes parsed markdown metadata, tags, headings, and resolved links for the
 * active vault.
 *
 * @public
 */
export class MetadataCache extends EventDispatcher<{
  /**
   * Called when a file has been indexed, and its (updated) cache is now
   * available.
   *
   * Note: This is not called when a file is renamed for performance reasons.
   * You must hook the vault rename event for those.
   *
   * @public
   */
  changed: [file: TFile, data: string, cache: CachedMetadata];
  /**
   * Called when a file has been deleted. A best-effort previous version of the
   * cached metadata is presented, but it could be null in case the file was not
   * successfully cached previously.
   *
   * @public
   */
  deleted: [file: TFile, prevCache: CachedMetadata | null];
  /** Called when the metadata has been loaded */
  loaded: [];
}> {
  processors: Map<string, Set<MetadataProcessor>> = new Map();
  projectionContributors: Set<IndexedProjectionContributor> = new Set();
  #fileCache: Record<string, { mtime: number; size: number; hash: string }> =
    $state({});

  #metadataCache: Record<string, CachedMetadata> = $state({});
  #resolvedLinks: Record<string, Record<string, number>> = $state({});
  #unresolvedLinks: Record<string, Record<string, number>> = $state({});
  readonly logger = logging.getLogger("cache");
  readonly legacyStorage: ScopedVaultStore;
  private lastPortableBackupWrite = 0;
  private disposed = false;
  private didLoad = false;
  private loadPromise: Promise<void> | null = null;
  private disposePromise: Promise<void> | null = null;
  private readonly pendingOperations = new Set<Promise<unknown>>();
  private readonly handleVaultChange = (
    event: string,
    file: TAbstractFile,
  ): void => this.handleChange(event, file);
  private readonly handleVaultRename = (
    file: TAbstractFile,
    oldPath: string,
  ): void => this.handleRename(file, oldPath);
  private readonly saveSnapshotDebounced = debounce(
    () => void this.saveSnapshotNow(),
    500,
  );

  constructor(readonly app: App) {
    super();
    this.legacyStorage = new ScopedVaultStore(
      getAdapterVaultId(app.vault.adapter),
      "metadata-cache",
    );
    app.vault.on("all", this.handleVaultChange);
    app.vault.on("rename", this.handleVaultRename);
  }

  get metadataCache() {
    return this.#metadataCache;
  }

  get resolvedLinks() {
    return this.#resolvedLinks;
  }

  get unresolvedLinks() {
    return this.#unresolvedLinks;
  }

  get fileCache() {
    return this.#fileCache;
  }

  get initialized(): boolean {
    return this.didLoad;
  }

  getAllItems(): Map<TFile, CachedMetadata> {
    const map: Map<TFile, CachedMetadata> = new Map();
    for (const [path, cache] of Object.entries(this.#fileCache)) {
      const item = this.#metadataCache[cache.hash];
      const file = this.app.vault.getFileByPath(path);
      if (item && file) {
        map.set(file, item);
      }
    }
    return map;
  }

  scheduleSnapshotSave(): void {
    if (this.disposed) return;
    this.saveSnapshotDebounced();
  }

  async flushSnapshotSave(): Promise<void> {
    this.saveSnapshotDebounced.cancel();
    await this.saveSnapshotNow({ forceBackup: true });
  }

  async dispose(options: { persist?: boolean } = {}): Promise<void> {
    if (this.disposePromise) return this.disposePromise;
    this.disposed = true;
    this.app.vault.off("all", this.handleVaultChange);
    this.app.vault.off("rename", this.handleVaultRename);
    this.saveSnapshotDebounced.cancel();
    this.disposePromise = (async () => {
      await Promise.allSettled([...this.pendingOperations]);
      if (options.persist !== false && this.didLoad) {
        await this.saveSnapshotNow({ forceBackup: true });
      }
    })();
    return this.disposePromise;
  }

  async saveSnapshotNow(
    options: { forceBackup?: boolean } = {},
  ): Promise<void> {
    const snapshot = this.toJSON();
    try {
      await this.app.appDatabase.saveMetadataSnapshot(snapshot);
    } catch (err) {
      console.error("Failure saving metadata cache", err);
      notify(`Failure saving metadata cache: ${err}`);
      return;
    }

    const shouldWriteBackup =
      options.forceBackup ||
      Date.now() - this.lastPortableBackupWrite >=
        METADATA_CACHE_BACKUP_THROTTLE_MS;
    if (!shouldWriteBackup) {
      return;
    }

    await this.savePortableBackup(snapshot).catch((err) => {
      this.logger.warn("Failed to write portable metadata backup", err);
    });
  }

  toJSON() {
    return {
      fileCache: $state.snapshot(this.#fileCache),
      metadataCache: $state.snapshot(this.metadataCache),
      resolvedLinks: $state.snapshot(this.resolvedLinks),
      unresolvedLinks: $state.snapshot(this.unresolvedLinks),
    };
  }

  private applySnapshot(snapshot: MetadataCacheSnapshot): void {
    if (this.disposed) return;
    this.didLoad = true;
    this.#fileCache = snapshot.fileCache;
    this.#metadataCache = snapshot.metadataCache as Record<
      string,
      CachedMetadata
    >;
    this.#resolvedLinks = snapshot.resolvedLinks;
    this.#unresolvedLinks = snapshot.unresolvedLinks;
  }

  private async loadPortableBackupSnapshot(): Promise<MetadataCacheSnapshot | null> {
    try {
      if (!(await this.app.vault.adapter.exists(METADATA_CACHE_BACKUP_PATH))) {
        return null;
      }
      const raw = await this.app.vault.adapter.read(METADATA_CACHE_BACKUP_PATH);
      return parseMetadataCacheBackup(raw)?.snapshot ?? null;
    } catch (err) {
      this.logger.warn("Failed to load portable metadata backup", err);
      return null;
    }
  }

  private async savePortableBackup(
    snapshot: MetadataCacheSnapshot,
  ): Promise<void> {
    const now = Date.now();
    let createdAt = now;
    try {
      const existingRaw = await this.app.vault.adapter.read(
        METADATA_CACHE_BACKUP_PATH,
      );
      createdAt = parseMetadataCacheBackup(existingRaw)?.createdAt ?? now;
    } catch {
      // Missing or invalid backups are overwritten with a fresh generated copy.
    }

    const backup: MetadataCacheBackupV1 = {
      kind: METADATA_CACHE_BACKUP_KIND,
      schemaVersion: METADATA_CACHE_BACKUP_SCHEMA_VERSION,
      appDatabaseSchemaVersion: APP_DATABASE_SCHEMA_VERSION,
      createdAt,
      updatedAt: now,
      sourceVaultId: getAdapterVaultId(this.app.vault.adapter),
      snapshot,
    };
    await this.app.vault.adapter.mkdir(dirname(METADATA_CACHE_BACKUP_PATH), {
      recursive: true,
    });
    await this.app.vault.adapter.write(
      METADATA_CACHE_BACKUP_PATH,
      `${JSON.stringify(backup)}\n`,
    );
    this.lastPortableBackupWrite = now;
  }

  private loadLegacySnapshot(): Promise<MetadataCacheSnapshot | null> {
    return this.legacyStorage
      .getMany<string>([
        "fileCache",
        "metadataCache",
        "metadataCache.resolvedLinks",
        "metadataCache.unresolvedLinks",
      ])
      .then(([fileCache, metadataCache, resolvedLinks, unresolvedLinks]) => {
        if (
          !fileCache &&
          !metadataCache &&
          !resolvedLinks &&
          !unresolvedLinks
        ) {
          return null;
        }
        return {
          fileCache: parseValue("fileCache", fileCache, this.#fileCache),
          metadataCache: parseValue(
            "metadataCache",
            metadataCache,
            this.#metadataCache,
          ),
          resolvedLinks: parseValue(
            "resolvedLinks",
            resolvedLinks,
            this.#resolvedLinks,
          ),
          unresolvedLinks: parseValue(
            "unresolvedLinks",
            unresolvedLinks,
            this.#unresolvedLinks,
          ),
        };
      })
      .catch((err) => {
        console.error("Failed to load metadataCache", err);
        return null;
      });
  }

  async load() {
    if (this.disposed) return;
    if (this.loadPromise) return this.loadPromise;
    this.loadPromise = this.performLoad();
    this.trackOperation(this.loadPromise);
    return this.loadPromise;
  }

  private async performLoad(): Promise<void> {
    await this.app.notifications.withProgress(
      {
        title: "Loading metadata cache",
        source: "Metadata",
        location: "status",
        persistOnError: true,
      },
      async (progress) => {
        if (this.disposed) return;
        progress.report({ message: "Opening metadata store" });
        await this.app.appDatabase.open();
        if (this.disposed) return;
        progress.report({ message: "Loading metadata snapshot" });
        const primarySnapshot = await this.loadPrimarySnapshot();
        if (this.disposed) return;
        if (primarySnapshot) {
          this.applySnapshot(primarySnapshot);
          this.trigger("loaded");
          void this.savePortableBackup(primarySnapshot).catch((err) => {
            this.logger.warn("Failed to refresh portable metadata backup", err);
          });
          await this.reconcileSnapshotWithVault(progress);
          return;
        }

        const portableBackupSnapshot = await this.loadPortableBackupSnapshot();
        if (this.disposed) return;
        if (portableBackupSnapshot) {
          this.applySnapshot(portableBackupSnapshot);
          await this.hydrateDatabaseFromSnapshot(portableBackupSnapshot);
          this.trigger("loaded");
          await this.reconcileSnapshotWithVault(progress);
          return;
        }

        const legacySnapshot = await this.loadLegacySnapshot();
        if (this.disposed) return;
        if (legacySnapshot) {
          this.applySnapshot(legacySnapshot);
          await this.hydrateDatabaseFromSnapshot(legacySnapshot);
          this.trigger("loaded");
          await this.reconcileSnapshotWithVault(progress);
          return;
        }

        progress.report({ message: "Rebuilding metadata cache" });
        await this.rebuild(progress);
        if (!this.disposed) this.didLoad = true;
      },
    );
  }

  private async loadPrimarySnapshot(): Promise<MetadataCacheSnapshot | null> {
    try {
      return await this.app.appDatabase.loadMetadataSnapshot();
    } catch (err) {
      this.logger.warn(
        "Failed to load metadata snapshot from app database",
        err,
      );
      return null;
    }
  }

  private async hydrateDatabaseFromSnapshot(
    snapshot: MetadataCacheSnapshot,
  ): Promise<void> {
    await this.app.appDatabase.saveMetadataSnapshot(snapshot).catch((err) => {
      this.logger.warn("Failed to persist loaded metadata snapshot", err);
    });

    for (const [path, entry] of Object.entries(snapshot.fileCache)) {
      const file = this.app.vault.getFileByPath(path);
      const cache = snapshot.metadataCache[entry.hash] as
        | CachedMetadata
        | undefined;
      if (!file || !cache) {
        continue;
      }
      await this.app.appDatabase
        .upsertIndexedFile(this.toDatabaseRecord(file, entry.hash, cache))
        .catch((err) => {
          this.logger.warn(
            `Failed to hydrate indexed metadata for ${path}`,
            err,
          );
        });
    }
    await this.savePortableBackup(snapshot).catch((err) => {
      this.logger.warn("Failed to write portable metadata backup", err);
    });
  }

  private async reconcileSnapshotWithVault(
    progress?: NotificationProgressHandle,
  ): Promise<void> {
    if (this.disposed) return;
    const cachedEntries = Object.entries({ ...this.fileCache });
    const missingFiles = this.app.vault
      .getFiles()
      .filter((file) => !this.fileCache[file.path]);
    const total = cachedEntries.length + missingFiles.length;
    let processed = 0;
    let changed = false;

    for (const [path, entry] of cachedEntries) {
      if (this.disposed) return;
      progress?.throwIfCancellationRequested();
      progress?.report({
        current: processed,
        total,
        message: path,
      });
      const file = this.app.vault.getFileByPath(path);
      if (!file) {
        delete this.fileCache[path];
        delete this.resolvedLinks[path];
        delete this.unresolvedLinks[path];
        delete this.metadataCache[entry.hash];
        await this.app.appDatabase.deleteIndexedFile(path).catch((err) => {
          this.logger.warn(`Failed to delete stale metadata for ${path}`, err);
        });
        changed = true;
      } else if (
        file.stat.mtime !== entry.mtime ||
        file.stat.size !== entry.size
      ) {
        changed = (await this.processFile(file)) || changed;
      }
      processed += 1;
      await yieldToUi();
    }

    for (const file of missingFiles) {
      if (this.disposed) return;
      progress?.throwIfCancellationRequested();
      progress?.report({
        current: processed,
        total,
        message: file.path,
      });
      changed = (await this.processFile(file)) || changed;
      processed += 1;
      await yieldToUi();
    }

    if (changed && !this.disposed) {
      progress?.report({
        current: processed,
        total,
        message: "Persisting metadata cache",
      });
      await this.saveSnapshotNow();
    }
  }

  getFileCache(file: TFile): CachedMetadata | null {
    return this.metadataCache[this.fileCache[file.path]?.hash] ?? null;
  }

  getCache(path: string): CachedMetadata | null {
    return this.metadataCache[this.fileCache[path]?.hash] ?? null;
  }

  getDirectReferencePaths(sourcePath: string): string[] {
    const cache = this.getCache(sourcePath);
    if (!cache) {
      return [];
    }

    const targets = new Set<string>();
    iterateCacheRefs(cache, (ref) => {
      const target = this.getFirstLinkpathDest(ref.link, sourcePath);
      if (target?.path) {
        targets.add(target.path);
      }
    });

    return uniquePaths(targets);
  }

  pathDirectlyReferences(sourcePath: string, targetPath: string): boolean {
    if (!sourcePath || !targetPath) {
      return false;
    }

    return this.getDirectReferencePaths(sourcePath).includes(targetPath);
  }

  getDirectReferencingPaths(targetPath: string): string[] {
    if (!targetPath) {
      return [];
    }

    const matches: string[] = [];
    for (const sourcePath of Object.keys(this.fileCache)) {
      if (this.pathDirectlyReferences(sourcePath, targetPath)) {
        matches.push(sourcePath);
      }
    }

    return uniquePaths(matches);
  }

  isDirectlyAffectedByPathChange(
    watchedPath: string | null | undefined,
    changedPath: string | null | undefined,
  ): boolean {
    if (!watchedPath || !changedPath) {
      return false;
    }

    return (
      watchedPath === changedPath ||
      this.pathDirectlyReferences(watchedPath, changedPath) ||
      this.pathDirectlyReferences(changedPath, watchedPath)
    );
  }

  getFirstLinkpathDest(linkpath: string, sourcePath: string): TFile | null {
    const parsed = parseLinktext(linkpath);
    const normalizedPath = normalizeVaultPath(parsed.path);
    if (!normalizedPath.length) {
      return null;
    }

    const sourceDir = normalizeVaultPath(
      sourcePath ? dirname(normalizeVaultPath(sourcePath)) : "",
    );
    const relativePath = sourceDir.length
      ? normalizeVaultPath(resolvePath(sourceDir, normalizedPath))
      : normalizedPath;
    const linkName = basename(normalizedPath);
    const basenamePath = linkName.replace(/\.(md|markdown)$/i, "");
    const candidates = [
      relativePath,
      `${relativePath}.md`,
      `${relativePath}.markdown`,
      normalizedPath,
      `${normalizedPath}.md`,
      `${normalizedPath}.markdown`,
      ...this.app.vault
        .getMarkdownFiles()
        .filter(
          (file) =>
            file.basename === basenamePath ||
            file.baseName === basenamePath ||
            file.path === normalizedPath,
        )
        .map((file) => file.path),
      ...this.app.vault
        .getFiles()
        .filter((file) => {
          const filePath = normalizeVaultPath(file.path);
          return (
            filePath.endsWith(`/${normalizedPath}`) ||
            filePath.endsWith(`/${normalizedPath}.md`) ||
            filePath.endsWith(`/${normalizedPath}.markdown`)
          );
        })
        .map((file) => file.path),
      ...this.app.vault
        .getFiles()
        .filter((file) => file.baseName === linkName)
        .map((file) => file.path),
    ];

    const dedupedCandidates = [...new Set(candidates.filter(Boolean))];
    for (const candidate of dedupedCandidates) {
      const file = this.app.vault.getFileByPath(candidate);
      if (file) return file;
    }
    return null;
  }

  fileToLinktext(
    file: TFile,
    sourcePath: string,
    omitMdExtension?: boolean,
  ): string {
    const vaultIndex: VaultIndex = {
      getFiles: () =>
        this.app.vault.getFiles().map((vaultFile) => ({
          path: vaultFile.path,
          basename: vaultFile.basename,
          extension: vaultFile.extension,
        })),
    };

    return getLinkPath(
      file.path,
      sourcePath,
      {
        ...defaultLinkSettings,
        omitMarkdownExtension:
          omitMdExtension ?? defaultLinkSettings.omitMarkdownExtension,
      },
      vaultIndex,
    );
  }

  rebuild(progress?: NotificationProgressHandle) {
    if (progress) {
      return this.performRebuild(progress);
    }
    return this.app.notifications.withProgress(
      {
        title: "Rebuilding metadata cache",
        source: "Metadata",
        location: "status",
        cancellable: true,
        persistOnError: true,
      },
      (handle) => this.performRebuild(handle),
    );
  }

  private async performRebuild(
    progress: NotificationProgressHandle,
  ): Promise<void> {
    clearObject(this.fileCache);
    clearObject(this.metadataCache);
    clearObject(this.resolvedLinks);
    clearObject(this.unresolvedLinks);

    const files = this.app.vault.getFiles();
    let processed = 0;
    for (const file of files) {
      if (this.disposed) return;
      progress.throwIfCancellationRequested();
      progress.report({
        current: processed,
        total: files.length,
        message: file.path,
      });
      await this.processFile(file);
      processed += 1;
      await yieldToUi();
    }
    if (this.disposed) return;
    progress.report({
      current: processed,
      total: files.length,
      message: "Persisting metadata cache",
    });
    await this.saveSnapshotNow({ forceBackup: true });
    this.trigger("loaded");
  }

  addProcessor(ext: string, processor: MetadataProcessor) {
    if (!ext?.trim()) return;
    ext = ext.trim().toLowerCase();
    if (!this.processors.has(ext)) {
      this.processors.set(ext, new Set());
    }
    this.processors.get(ext)!.add(processor);
  }

  removeProcessor(ext: string, processor: MetadataProcessor): boolean {
    if (!ext?.trim()) return false;
    ext = ext.trim().toLowerCase();
    if (!this.processors.has(ext)) return false;
    return this.processors.get(ext)!.delete(processor);
  }

  private async projectRegisteredIndexes(
    file: TFile,
    content: string,
    cache: CachedMetadata,
    hash: string,
  ): Promise<void> {
    const fileRef = {
      path: file.path,
      extension: file.extension,
      name: file.name,
    };
    for (const entry of this.app.indexProjections.matching(fileRef, cache)) {
      try {
        const result = await entry.registration.project({
          file: fileRef,
          content,
          cache,
        });
        await this.app.appDatabase.replaceProjectionSource({
          projectionId: entry.projectionId,
          sourcePath: file.path,
          sourceHash: hash,
          rows: result.rows,
          edges: result.edges,
        });
      } catch (error) {
        await this.app.appDatabase.markProjectionSourceError({
          projectionId: entry.projectionId,
          sourcePath: file.path,
          sourceHash: hash,
          error: error instanceof Error ? error.message : String(error),
        });
      }
    }
  }

  addIndexedProjectionContributor(contributor: IndexedProjectionContributor) {
    this.projectionContributors.add(contributor);
  }

  removeIndexedProjectionContributor(
    contributor: IndexedProjectionContributor,
  ): boolean {
    return this.projectionContributors.delete(contributor);
  }

  private handleChange(event: string, file: TAbstractFile) {
    if (this.disposed) return;
    if (!(file instanceof TFile)) return;
    switch (event) {
      case "create":
      case "modify":
        this.trackOperation(
          this.processFile(file).then((changed) => {
            if (changed) this.scheduleSnapshotSave();
          }),
        );
        break;
      case "delete":
        const existing = this.fileCache[file.path];
        if (existing) {
          this.trigger("deleted", file, this.metadataCache[existing.hash]);
          delete this.fileCache[file.path];
          delete this.resolvedLinks[file.path];
          delete this.unresolvedLinks[file.path];
          delete this.metadataCache[existing.hash];
          this.trackOperation(
            this.app.appDatabase.deleteIndexedFile(file.path),
          );
          this.scheduleSnapshotSave();
        }
        break;
    }
  }

  private handleRename(file: TAbstractFile, oldPath: string) {
    if (this.disposed) return;
    if (!(file instanceof TFile)) return;
    const existing = this.fileCache[oldPath];
    if (!existing) return;
    this.fileCache[file.path] = {
      ...existing,
      mtime: file.stat.mtime,
      size: file.stat.size,
    };
    delete this.fileCache[oldPath];
    if (this.resolvedLinks[oldPath]) {
      this.resolvedLinks[file.path] = this.resolvedLinks[oldPath];
      delete this.resolvedLinks[oldPath];
    }
    if (this.unresolvedLinks[oldPath]) {
      this.unresolvedLinks[file.path] = this.unresolvedLinks[oldPath];
      delete this.unresolvedLinks[oldPath];
    }
    this.trackOperation(
      this.app.appDatabase.renameIndexedFile(oldPath, file.path),
    );
    this.scheduleSnapshotSave();
  }

  private trackOperation(operation: Promise<unknown>): void {
    this.pendingOperations.add(operation);
    void operation
      .catch((error) => {
        this.logger.warn("Metadata cache background operation failed", error);
      })
      .finally(() => {
        this.pendingOperations.delete(operation);
      });
  }

  private async processFile(file: TFile | null): Promise<boolean> {
    if (!file) return false;
    file = this.app.vault.getFileByPath(file.path);
    if (!file) return false;

    const processors = this.processors.get(file.extension.toLowerCase());
    if (!processors || !processors.size) return false;

    const content = await this.app.vault.read(file);
    const hash = md5(content);
    const existing = this.fileCache[file.path];
    if (existing && existing.hash === hash) return false;
    let cachedMetadata = await this.read(content, file);
    if (cachedMetadata) {
      this.metadataCache[hash] = cachedMetadata;
      this.fileCache[file.path] = {
        mtime: file.stat.mtime,
        size: file.stat.size,
        hash,
      };
      this.processLink(file);
      const record = this.toDatabaseRecord(file, hash, cachedMetadata);
      await this.app.appDatabase.upsertIndexedFile(record);
      await this.projectRegisteredIndexes(file, content, cachedMetadata, hash);
      this.trigger("changed", file, content, cachedMetadata);
    }
    if (existing && existing.hash !== hash) {
      delete this.metadataCache[existing.hash];
    }
    this.logger.debug("Processing file", file.path);
    return Boolean(cachedMetadata);
  }

  private extractLink(path: string) {
    const [segment, description] = path.split("|", 2);
    const [url, sectionId] = segment.split("#", 2);
    return {
      url,
      sectionId,
      displayText:
        description || basename(path) + (sectionId ? ` > ${sectionId}` : ""),
    };
  }

  private processLink(file: TFile) {
    const cachedMetadata = this.metadataCache[this.fileCache[file.path]?.hash];
    if (!cachedMetadata) return;
    this.resolvedLinks[file.path] = {};
    this.unresolvedLinks[file.path] = {};
    const links = cachedMetadata.links;
    if (!links?.length) return;
    links.forEach((link) => {
      const spec = this.extractLink(link.link);
      const path =
        ([...this.processors.keys()]
          .map((ext) => `${spec.url}.${ext}`)
          .find((path) => this.app.vault.getFileByPath(path)) ??
        this.app.vault.getFileByPath(spec.url))
          ? spec.url
          : null;

      if (path) {
        this.resolvedLinks[file.path][path] ||= 0;
        this.resolvedLinks[file.path][path] += 1;
      } else {
        this.unresolvedLinks[file.path][link.link] ||= 0;
        this.unresolvedLinks[file.path][link.link] += 1;
      }
    });
  }

  private toDatabaseRecord(
    file: TFile,
    hash: string,
    cache: CachedMetadata,
  ): AppDatabaseIndexedFile {
    const refs: AppDatabaseLinkRecord[] = [];
    (cache.links ?? []).forEach((ref, ordinal) => {
      const spec = this.extractLink(ref.link);
      refs.push({
        sourcePath: file.path,
        targetText: ref.link,
        resolvedTargetPath:
          this.getFirstLinkpathDest(spec.url, file.path)?.path ?? null,
        type: "link",
        position: ref.position,
        count: 1,
        heading: ref.heading ?? null,
        kind: structuralLinkKind(ref.heading),
        ordinal,
      });
    });
    for (const ref of cache.embeds ?? []) {
      const spec = this.extractLink(ref.link);
      refs.push({
        sourcePath: file.path,
        targetText: ref.link,
        resolvedTargetPath:
          this.getFirstLinkpathDest(spec.url, file.path)?.path ?? null,
        type: "embed",
        position: ref.position,
        count: 1,
      });
    }

    const tags: AppDatabaseTagRecord[] = (cache.tags ?? []).map((tag) => {
      const parts = tagParts(tag.tag);
      return {
        path: file.path,
        tag: tag.tag,
        parts: parts.parts,
        hierarchy: parts.hierarchy,
        position: tag.position,
      };
    });

    const properties: AppDatabasePropertyRecord[] = Object.entries(
      cache.frontmatter ?? {},
    ).map(([name, value]) => ({
      path: file.path,
      name,
      inferredType: frontmatterValueType(value),
      declaredType: this.app.metadataTypeManager?.types?.[name]?.type,
      value,
    }));

    return {
      file: {
        path: file.path,
        normalizedPath: file.path,
        extension: file.extension.toLowerCase(),
        mtime: file.stat.mtime,
        size: file.stat.size,
        hash,
        indexed: true,
      },
      metadata: {
        path: file.path,
        hash,
        parserVersion: "metadata-cache-v1",
        metadata: cache,
      },
      links: refs,
      tags,
      properties,
    };
  }

  async processFileCache(
    file: TFile | string | null,
  ): Promise<CachedMetadata | null> {
    if (!file) return null;
    if (typeof file === "string") {
      return this.processFileCache(this.app.vault.getFileByPath(file));
    }
    return this.read(await this.app.vault.read(file), file);
  }

  async read(content: string, file: TFile) {
    const processors = this.processors.get(file.extension.toLowerCase());
    if (!processors || !processors.size) return null;

    let cachedMetadata: CachedMetadata = {};
    for (const processor of processors) {
      const cache = await processor.read(content, {
        file,
        cache: cachedMetadata,
      });
      if (cache) {
        cachedMetadata = cache;
      }
    }
    return cachedMetadata;
  }

  writeFrontmatter(file: TFile, data: FrontMatterCache) {
    const processors = this.processors.get(file.extension.toLowerCase());
    if (!processors || !processors.size) return "";

    for (const processor of processors) {
      const value = processor.write(data);
      if (value) {
        return value;
      }
    }
    return "";
  }
}

export function getAllTags(cache: CachedMetadata): string[] | null {
  return (cache.tags || []).map((it) => it.tag);
}
