// This file was generated by lezer-generator. You probably shouldn't edit it.
import { LRParser } from "@lezer/lr";
export const parser = LRParser.deserialize({
  version: 14,
  states:
    "%jQVQPOOOqQPO'#CdOxQPO'#CfO!pQPO'#CiO!xQPO'#CeOOQO'#Cc'#CcOOQO'#Ca'#CaOYQPO'#CaOOQO'#Ct'#CtO!}QPO'#C`O#[QPO'#C_OOQO'#C^'#C^QOQPOOOOQO,59O,59OO#gQPO,59OOOQO'#Cj'#CjO#lQPO,59TO#tQPO,59POOQO,58{,58{OOQO-E6r-E6rOVQPO'#CuO$]QPO,58yOOQO1G.j1G.jOOQO1G.o1G.oO$hQPO1G.oOOQO'#Ch'#ChOOQO1G.k1G.kOOQO,59a,59aOOQO-E6s-E6sO%PQPO'#CmOOQO'#Cl'#ClO%_QPO7+$ZOOQO'#Co'#CoOOQO,59X,59XOOQO<<Gu<<Gu",
  stateData:
    "%k~OlOS~OUVOZQO_TOdTOeTOfTOmPOpRO~On]O~PVOUVXZVX_VXdVXeVXfVXgVXjVXmVXoYXpVXnVX~OZ_O__O~OoaO~OgSXjSXnSX~PVOgdOjRXnRX~OnfO~OohOqgO~OZiO_iOdiOeiOfiOmPOpRO~OgdOjRanRa~OZnO_nObmOdnOenOfnOmPO~OZpO_pOdpOepO~OqrO~OgdZbeZ~",
  goto: "#njPPkqu|P!S!]!j!qP!x!{#VP#Y!gP#]PPPP#`#hQ[OR^PTZOPSYOPRkdXWOPXdWUOPXdRbVYTOPVXdQiaRnhZTOPVXdZSOPVXdRjaYTOPVXdRiaR`RRohRqmUXOPdRcXQeYRle",
  nodeNames:
    "⚠ Query Expression OrExpression AndExpression PrefixExpression Negation PrimaryExpression Group FieldExpression FieldName Identifier FieldValue PropertyExpression PropertyName Phrase PropertyValue Comparison ComparisonOperator ComparisonValue NullKeyword Word Regex OrKeyword",
  maxTerm: 33,
  skippedNodes: [0],
  repeatNodeCount: 2,
  tokenData:
    "1q~RpX^#Vpq#Vrs#zst&sxy'byz'gz{&s}!O'l!O!P&s!P!Q'q!Q![*j![!],R!^!_,W!`!a,W!a!b&s!c!q*j!q!r,e!r!}*j!}#O.T#P#Q.Y#R#S*j#T#b*j#b#c._#c#o*j#y#z#V$f$g#V#BY#BZ#V$IS$I_#V$I|$JO#V$JT$JU#V$KV$KW#V&FU&FV#V~#[Yl~X^#Vpq#V#y#z#V$f$g#V#BY#BZ#V$IS$I_#V$I|$JO#V$JT$JU#V$KV$KW#V&FU&FV#V~#}XOY#zZ]#z^r#zrs$js#O#z#O#P$o#P;'S#z;'S;=`&m<%lO#z~$oO_~~$rmOX#zX^#z^p#zpq#zq!Q#z!Q![#z![!c#z!c!}#z!}#T#z#T#o#z#o#y#z#y#z#z#z$f#z$f$g#z$g#BY#z#BY#BZ#z#BZ$IS#z$IS$I_#z$I_$I|#z$I|$JO#z$JO$JT#z$JT$JU#z$JU$KV#z$KV$KW#z$KW&FU#z&FU&FV#z&FV;'S#z;'S;=`&m<%lO#z~&pP;=`<%l#z~&xWe~st&sz{&s!O!P&s!Q![&s!a!b&s!c!}&s#R#S&s#T#o&s~'gOm~~'lOn~~'qOU~~'tXOY'qZ]'q^!P'q!P!Q(a!Q#O'q#O#P(f#P;'S'q;'S;=`*d<%lO'q~(fOf~~(imOX'qX^'q^p'qpq'qq!Q'q!Q!['q![!c'q!c!}'q!}#T'q#T#o'q#o#y'q#y#z'q#z$f'q$f$g'q$g#BY'q#BY#BZ'q#BZ$IS'q$IS$I_'q$I_$I|'q$I|$JO'q$JO$JT'q$JT$JU'q$JU$KV'q$KV$KW'q$KW&FU'q&FU&FV'q&FV;'S'q;'S;=`*d<%lO'q~*gP;=`<%l'q~*qXZ~e~st&sz{&s}!O+^!O!P&s!Q![*j!a!b&s!c!}*j#R#S*j#T#o*j~+aS!Q![+m!c!}+m#R#S+m#T#o+m~+rTZ~}!O+^!Q![+m!c!}+m#R#S+m#T#o+m~,WOo~~,]Pb~!_!`,`~,eOb~~,lZZ~e~st&sz{&s}!O+^!O!P&s!Q![*j!a!b&s!c!t*j!t!u-_!u!}*j#R#S*j#T#o*j~-hXg~Z~e~st&sz{&s}!O+^!O!P&s!Q![*j!a!b&s!c!}*j#R#S*j#T#o*j~.YOp~~._Oq~~.fZZ~e~st&sz{&s}!O+^!O!P&s!Q![*j!a!b&s!c!}*j#R#S*j#T#i*j#i#j/X#j#o*j~/`ZZ~e~st&sz{&s}!O+^!O!P&s!Q![*j!a!b&s!c!}*j#R#S*j#T#`*j#`#a0R#a#o*j~0YZZ~e~st&sz{&s}!O+^!O!P&s!Q![*j!a!b&s!c!}*j#R#S*j#T#`*j#`#a0{#a#o*j~1UXd~Z~e~st&sz{&s}!O+^!O!P&s!Q![*j!a!b&s!c!}*j#R#S*j#T#o*j",
  tokenizers: [0],
  topRules: { Query: [0, 1] },
  tokenPrec: 204,
});
