// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
export const parser = LRParser.deserialize({
  version: 14,
  states: "%pQVQPOOOtQPO'#CdO{QPO'#CfO!vQPO'#CiO#OQPO'#CeOOQO'#Cc'#CcOOQO'#Ca'#CaOYQPO'#CaOOQO'#Cu'#CuO#TQPO'#C`O#bQPO'#C_OOQO'#C^'#C^QOQPOOOOQO,59O,59OO#mQPO,59OOOQO'#Cj'#CjO#rQPO,59TO#zQPO,59POOQO,58{,58{OOQO-E6s-E6sOVQPO'#CvO$fQPO,58yOOQO1G.j1G.jO$qQPO1G.oO%lQPO1G.oOOQO'#Ch'#ChOOQO1G.k1G.kOOQO,59b,59bOOQO-E6t-E6tO%lQPO7+$ZO&WQPO'#CmOOQO'#Cl'#ClO&iQPO7+$ZOOQO<<Gu<<GuOOQO'#Co'#CoOOQO,59X,59X",
  stateData: "&v~OmOS~OUVOZQO_TOdTOeTOfTOgTOnPOqRO~Oo]O~PVOUVXZVX_VXdVXeVXfVXgVXhVXkVXnVXpYXqVXoVX~OZ_O__O~OpaO~OhSXkSXoSX~PVOhdOkRXoRX~OofO~OphOrgO~OZiO_iOdiOeiOfiOgiOnPOqRO~OhdOkRaoRa~OpmOU]iZ]i_]id]ie]if]ig]ih]ik]in]iq]io]i~OZoO_oObnOdoOeoOfoOgoOnPO~OZrO_rOdrOerOfrO~OrqO~OhdeZbfZ~",
  goto: "#skPPlrv}P!T!^!l!sP!z!}#XP#[!hP#bPPPPP#e#mQ[OR^PTZOPSYOPRkdXWOPXdWUOPXdRbVYTOPVXdQiaTohmZTOPVXdZSOPVXdRjaYTOPVXdRiaR`RQphRqmRsnUXOPdRcXQeYRle",
  nodeNames: "⚠ Query Expression OrExpression AndExpression PrefixExpression Negation PrimaryExpression Group FieldExpression FieldName Identifier FieldValue PropertyExpression PropertyName Phrase PropertyValue Comparison ComparisonOperator ComparisonValue NullKeyword SlashWord Word Regex OrKeyword",
  maxTerm: 34,
  skippedNodes: [0],
  repeatNodeCount: 2,
  tokenData: "2}~RpX^#Vpq#Vrs#zst&sxy(Xyz(^z{&s}!O(c!O!P&s!P!Q(h!Q![+a![!],{!^!_-Q!`!a-Q!a!b&s!c!q+a!q!r-_!r!}+a!}#O/T#P#Q/Y#R#S+a#T#b+a#b#c/_#c#o+a#y#z#V$f$g#V#BY#BZ#V$IS$I_#V$I|$JO#V$JT$JU#V$KV$KW#V&FU&FV#V~#[Ym~X^#Vpq#V#y#z#V$f$g#V#BY#BZ#V$IS$I_#V$I|$JO#V$JT$JU#V$KV$KW#V&FU&FV#V~#}XOY#zZ]#z^r#zrs$js#O#z#O#P$o#P;'S#z;'S;=`&m<%lO#z~$oO_~~$rmOX#zX^#z^p#zpq#zq!Q#z!Q![#z![!c#z!c!}#z!}#T#z#T#o#z#o#y#z#y#z#z#z$f#z$f$g#z$g#BY#z#BY#BZ#z#BZ$IS#z$IS$I_#z$I_$I|#z$I|$JO#z$JO$JT#z$JT$JU#z$JU$KV#z$KV$KW#z$KW&FU#z&FU&FV#z&FV;'S#z;'S;=`&m<%lO#z~&pP;=`<%l#z~&xXf~st&sz{&s!O!P&s!P!Q'e!Q![&s!a!b&s!c!}&s#R#S&s#T#o&s~'lXe~f~st'ez{'e!O!P'e!P!Q'e!Q!['e!a!b'e!c!}'e#R#S'e#T#o'e~(^On~~(cOo~~(hOU~~(kXOY(hZ](h^!P(h!P!Q)W!Q#O(h#O#P)]#P;'S(h;'S;=`+Z<%lO(h~)]Og~~)`mOX(hX^(h^p(hpq(hq!Q(h!Q![(h![!c(h!c!}(h!}#T(h#T#o(h#o#y(h#y#z(h#z$f(h$f$g(h$g#BY(h#BY#BZ(h#BZ$IS(h$IS$I_(h$I_$I|(h$I|$JO(h$JO$JT(h$JT$JU(h$JU$KV(h$KV$KW(h$KW&FU(h&FU&FV(h&FV;'S(h;'S;=`+Z<%lO(h~+^P;=`<%l(h~+hYZ~f~st&sz{&s}!O,W!O!P&s!P!Q'e!Q![+a!a!b&s!c!}+a#R#S+a#T#o+a~,ZS!Q![,g!c!},g#R#S,g#T#o,g~,lTZ~}!O,W!Q![,g!c!},g#R#S,g#T#o,g~-QOp~~-VPb~!_!`-Y~-_Ob~~-f[Z~f~st&sz{&s}!O,W!O!P&s!P!Q'e!Q![+a!a!b&s!c!t+a!t!u.[!u!}+a#R#S+a#T#o+a~.eYh~Z~f~st&sz{&s}!O,W!O!P&s!P!Q'e!Q![+a!a!b&s!c!}+a#R#S+a#T#o+a~/YOq~~/_Or~~/f[Z~f~st&sz{&s}!O,W!O!P&s!P!Q'e!Q![+a!a!b&s!c!}+a#R#S+a#T#i+a#i#j0[#j#o+a~0c[Z~f~st&sz{&s}!O,W!O!P&s!P!Q'e!Q![+a!a!b&s!c!}+a#R#S+a#T#`+a#`#a1X#a#o+a~1`[Z~f~st&sz{&s}!O,W!O!P&s!P!Q'e!Q![+a!a!b&s!c!}+a#R#S+a#T#`+a#`#a2U#a#o+a~2_Yd~Z~f~st&sz{&s}!O,W!O!P&s!P!Q'e!Q![+a!a!b&s!c!}+a#R#S+a#T#o+a",
  tokenizers: [0],
  topRules: {"Query":[0,1]},
  tokenPrec: 260
})
