[book]
title = "Lapis Notes (Minimal) System Specification"
authors = ["Lapis contributors"]
language = "en"
src = "src"

[build]
build-dir = "book"

[output.html]
default-theme = "light"
preferred-dark-theme = "navy"
