export const pluginPanelPlacements = [
  {
    exportName: "MiddleTopTabs",
    suffix: "",
    story: "middle-top-tabs",
    title: "Middle (Top Tabs)",
  },
  {
    exportName: "StackedTabs",
    suffix: "-stacked-tabs",
    story: "stacked-tabs",
    title: "Stacked Tabs",
  },
  {
    exportName: "LeftSidebar",
    suffix: "-left-sidebar",
    story: "left-sidebar",
    title: "Left Sidebar",
  },
  {
    exportName: "RightSidebar",
    suffix: "-right-sidebar",
    story: "right-sidebar",
    title: "Right Sidebar",
  },
  {
    exportName: "BottomPanel",
    suffix: "-bottom-panel",
    story: "bottom-panel",
    title: "Bottom Panel",
  },
  {
    exportName: "SidebarGroup",
    suffix: "-sidebar-group",
    story: "sidebar-group",
    title: "Sidebar As a Group",
  },
];

export const pluginPanelFamilies = [
  {
    kind: "ai-chat",
    plugin: "AI",
    panel: "Chat",
    title: "AI Chat",
    spec: "spec/src/plugins/ai/index.md",
    publicSurface: "@lapis-notes/ai",
    sourceFile: "packages/plugins/plugin-ai/src/lib/ai-plugin.ts",
    commandId: "ai:open-chat",
    commandToken: 'id: "open-chat"',
    storyFile: "stories/plugins/ai/panels/Chat.stories.ts",
    storyPrefix: "plugins-ai-panels-chat",
  },
  {
    kind: "ai-history",
    plugin: "AI",
    panel: "History",
    title: "AI History",
    spec: "spec/src/plugins/ai/index.md",
    publicSurface: "@lapis-notes/ai",
    sourceFile: "packages/plugins/plugin-ai/src/lib/ai-plugin.ts",
    commandId: "ai:open-history",
    commandToken: 'id: "open-history"',
    storyFile: "stories/plugins/ai/panels/History.stories.ts",
    storyPrefix: "plugins-ai-panels-history",
  },
  {
    kind: "ai-catalog",
    plugin: "AI",
    panel: "Catalog",
    title: "AI Catalog",
    spec: "spec/src/plugins/ai/index.md",
    publicSurface: "@lapis-notes/ai",
    sourceFile: "packages/plugins/plugin-ai/src/lib/ai-plugin.ts",
    commandId: "ai:open-catalog",
    commandToken: 'id: "open-catalog"',
    storyFile: "stories/plugins/ai/panels/Catalog.stories.ts",
    storyPrefix: "plugins-ai-panels-catalog",
  },
  {
    kind: "explorer",
    plugin: "Explorer",
    panel: "Explorer",
    title: "Explorer",
    spec: "spec/src/plugins/explorer/index.md",
    publicSurface: "@lapis-notes/file-explorer",
    sourceFile: "packages/file-explorer/src/lib/index.ts",
    commandId: "lapis-file-explorer:open-explorer",
    commandToken: 'id: "open-explorer"',
    storyFile: "stories/plugins/explorer/panels/Explorer.stories.ts",
    storyPrefix: "plugins-explorer-panels-explorer",
  },
  {
    kind: "all-properties",
    plugin: "Markdown",
    panel: "All Properties",
    title: "All Properties",
    spec: "spec/src/plugins/markdown/panels/all-properties.md",
    publicSurface: "@lapis-notes/markdown",
    sourceFile: "packages/plugins/plugin-markdown/src/lib/view-commands.ts",
    commandId: "markdown:open-all-properties",
    commandToken: 'id: "open-all-properties"',
    storyFile: "stories/plugins/markdown/panels/AllProperties.stories.ts",
    storyPrefix: "plugins-markdown-panels-all-properties",
  },
  {
    kind: "file-properties",
    plugin: "Markdown",
    panel: "File Properties",
    title: "File Properties",
    spec: "spec/src/plugins/markdown/panels/file-properties.md",
    publicSurface: "@lapis-notes/markdown",
    sourceFile: "packages/plugins/plugin-markdown/src/lib/view-commands.ts",
    commandId: "markdown:open-file-properties",
    commandToken: 'id: "open-file-properties"',
    storyFile: "stories/plugins/markdown/panels/FileProperties.stories.ts",
    storyPrefix: "plugins-markdown-panels-file-properties",
  },
  {
    kind: "outline",
    plugin: "Markdown",
    panel: "Outline",
    title: "Outline",
    spec: "spec/src/plugins/markdown/panels/outline.md",
    publicSurface: "@lapis-notes/markdown",
    sourceFile: "packages/plugins/plugin-markdown/src/lib/view-commands.ts",
    commandId: "markdown:open-outline",
    commandToken: 'id: "open-outline"',
    storyFile: "stories/plugins/markdown/panels/Outline.stories.ts",
    storyPrefix: "plugins-markdown-panels-outline",
  },
  {
    kind: "backlinks",
    plugin: "Markdown",
    panel: "Backlinks",
    title: "Backlinks",
    spec: "spec/src/plugins/markdown/panels/backlinks.md",
    publicSurface: "@lapis-notes/markdown",
    sourceFile: "packages/plugins/plugin-markdown/src/lib/view-commands.ts",
    commandId: "markdown:open-backlinks",
    commandToken: 'id: "open-backlinks"',
    storyFile: "stories/plugins/markdown/panels/Backlinks.stories.ts",
    storyPrefix: "plugins-markdown-panels-backlinks",
  },
  {
    kind: "outgoing-links",
    plugin: "Markdown",
    panel: "Outgoing Links",
    title: "Outgoing Links",
    spec: "spec/src/plugins/markdown/panels/outgoing-links.md",
    publicSurface: "@lapis-notes/markdown",
    sourceFile: "packages/plugins/plugin-markdown/src/lib/view-commands.ts",
    commandId: "markdown:open-outgoing-links",
    commandToken: 'id: "open-outgoing-links"',
    storyFile: "stories/plugins/markdown/panels/OutgoingLinks.stories.ts",
    storyPrefix: "plugins-markdown-panels-outgoing-links",
  },
  {
    kind: "tags",
    plugin: "Markdown",
    panel: "Tags",
    title: "Tags",
    spec: "spec/src/plugins/markdown/panels/tags.md",
    publicSurface: "@lapis-notes/markdown",
    sourceFile: "packages/plugins/plugin-markdown/src/lib/view-commands.ts",
    commandId: "markdown:open-tags",
    commandToken: 'id: "open-tags"',
    storyFile: "stories/plugins/markdown/panels/Tags.stories.ts",
    storyPrefix: "plugins-markdown-panels-tags",
  },
  {
    kind: "search",
    plugin: "Search",
    panel: "Search",
    title: "Search",
    spec: "spec/src/plugins/search/index.md",
    publicSurface: "@lapis-notes/search",
    sourceFile: "packages/plugins/plugin-search/src/lib/search-plugin.ts",
    commandId: "search:open-search",
    commandToken: 'id: "open-search"',
    storyFile: "stories/plugins/search/panels/Search.stories.ts",
    storyPrefix: "plugins-search-panels-search",
  },
  {
    kind: "bookmarks",
    plugin: "Bookmarks",
    panel: "Bookmarks",
    title: "Bookmarks",
    spec: "spec/src/plugins/bookmarks/index.md",
    publicSurface: "@lapis-notes/bookmarks",
    sourceFile: "packages/plugins/plugin-bookmarks/src/lib/bookmarks-plugin.ts",
    commandId: "bookmarks:open-bookmarks",
    commandToken: 'id: "open-bookmarks"',
    storyFile: "stories/plugins/bookmarks/panels/Bookmarks.stories.ts",
    storyPrefix: "plugins-bookmarks-panels-bookmarks",
  },
  {
    kind: "history",
    plugin: "History",
    panel: "History",
    title: "History",
    spec: "spec/src/plugins/history/index.md",
    publicSurface: "@lapis-notes/history",
    sourceFile: "packages/plugins/plugin-history/src/lib/history-plugin.ts",
    commandId: "history:open-file-history",
    commandToken: 'id: "open-file-history"',
    storyFile: "stories/plugins/history/panels/History.stories.ts",
    storyPrefix: "plugins-history-panels-history",
  },
];

export const pluginPanelCatalog = pluginPanelFamilies.flatMap((family) =>
  pluginPanelPlacements.map((placement) => ({
    id: `plugin-panel-${family.kind}${placement.suffix}`,
    title: `${family.title}: ${placement.title}`,
    spec: family.spec,
    publicSurface: family.publicSurface,
    storyId: `${family.storyPrefix}--${placement.story}`,
  })),
);
