export const storybookFirstPartyPackageExcludes = [
  "@lapis-notes/api",
  "@lapis-notes/ui",
  "@lapis-notes/workspace",
  "@lapis-notes/file-explorer",
  "@lapis-notes/language-service",
  "@lapis-notes/app-profile",
  "@lapis-notes/markdown",
  "@lapismd/design-core",
] as const;

export const storybookPackedDependencyIncludes = [
  "@lapis-notes/api > eventemitter3",
  "@lapismd/mira/**",
  "@lapismd/design-core > tailwind-merge",
  "@lapismd/mira > tailwind-merge",
  "@lapismd/mira-plugin-mermaid > @braintree/sanitize-url",
  "@lapismd/mira-plugin-mermaid > dayjs",
  "@lapismd/mira-plugin-mermaid > fastdom",
  "@lapismd/mira-plugin-mermaid > fastdom/extensions/fastdom-promised.js",
  "@codemirror/commands",
  "@codemirror/language",
  "@codemirror/lint",
  "@codemirror/search",
  "@codemirror/state",
  "@codemirror/view",
  "@lapis-notes/api > @huggingface/transformers",
  "@lapis-notes/api > @iconify-json/lucide",
  "@lapis-notes/api > @iconify/utils",
  "@lapis-notes/api > @tanstack/virtual-core",
  "@lapis-notes/api > fflate",
  "@lapis-notes/api > i18next",
  "@lapis-notes/api > lodash-es",
  "@lapis-notes/api > lodash-es/debounce",
  "@lapis-notes/api > luxon",
  "@lapis-notes/api > minimatch",
  "@lapis-notes/api > svelte-sonner",
  "@lapis-notes/api > tailwind-merge",
  "@lapis-notes/api > zod",
  "@lapis-notes/spellcheck > harper.js/binary",
  "@lapis-notes/ui > fuse.js",
  "@lezer/highlight",
  "@lezer/lr",
  "@lucide/svelte/icons/alert-triangle",
  "@lucide/svelte/icons/arrow-left",
  "@lucide/svelte/icons/arrow-up-circle",
  "@lucide/svelte/icons/book-open",
  "@lucide/svelte/icons/calendar-clock",
  "@lucide/svelte/icons/circle-check",
  "@lucide/svelte/icons/check-circle-2",
  "@lucide/svelte/icons/check",
  "@lucide/svelte/icons/chevron-down",
  "@lucide/svelte/icons/chevron-right",
  "@lucide/svelte/icons/chevron-up",
  "@lucide/svelte/icons/chevrons-up-down",
  "@lucide/svelte/icons/download",
  "@lucide/svelte/icons/external-link",
  "@lucide/svelte/icons/globe-2",
  "@lucide/svelte/icons/monitor",
  "@lucide/svelte/icons/package",
  "@lucide/svelte/icons/power",
  "@lucide/svelte/icons/puzzle",
  "@lucide/svelte/icons/refresh-cw",
  "@lucide/svelte/icons/rotate-cw",
  "@lucide/svelte/icons/search",
  "@lucide/svelte/icons/search-x",
  "@lucide/svelte/icons/settings",
  "@lucide/svelte/icons/shield-alert",
  "@lucide/svelte/icons/shield-check",
  "@lucide/svelte/icons/sliders-horizontal",
  "@lucide/svelte/icons/sparkles",
  "@lucide/svelte/icons/tag",
  "@lucide/svelte/icons/trash-2",
  "@lucide/svelte/icons/upload",
  "@lucide/svelte/icons/users-round",
  "bits-ui",
  "debug",
  "extend",
] as const;
